# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

name: Ryosuke Tanaka
email: # you@example.com
description: rysk's personal page
url: https://profile.dev.rysk.jp
last_updated: true # 最終更新日を表示

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# remote_theme: alshedivat/al-folio

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: true # OpenGraph情報を含める
serve_schema_org: true # Schema.org情報を含める

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: rysk-tanaka
twitter_username: # あなたのTwitterユーザー名
linkedin_username: ryosuke-tanaka-540942287
scholar_userid: # あなたのGoogle Scholarユーザー名

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: My Blog
blog_description: # 技術関連の投稿や個人的な考察

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true
    permalink: /projects/:path/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:title/

# Pagination
pagination:
  enabled: true

# Comments
disqus_shortname: # コメント機能を有効にする場合、あなたのDisqus短縮名

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------

jquery_version: "1.12.4"
katex_version: "0.11.1"
anchorjs_version: "3.2.2"

# ネイビーを基調としたカラーテーマの設定
theme_color: navy
